apiVersion: apps/v1
kind: Deployment
metadata:
  name: s3proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: backend
      app: s3proxy
  template:
    metadata:
      labels:
        tier: backend
        app: s3proxy
    spec:
      containers:
      - name: s3proxy
        image: andrewgaul/s3proxy
        env:
        # Settings to configure s3proxy with local Azurite backend
        - name: JCLOUDS_PROVIDER
          value: azureblob
        - name: JCLOUDS_IDENTITY
          value: devstoreaccount1
        - name: JCLOUDS_ENDPOINT
          value: http://storage-azurite-service:10000/devstoreaccount1
        - name: JCLOUDS_CREDENTIAL
          value: changeme
        # Settings to configure s3proxy with filesystem storage backend
        # - name: JCLOUDSS_PROVIDER
        #   value: filesystem
        # - name: JCLOUDS_FILESYSTEM_BASEDIR
        #   value: /tmp/s3proxy
        # Settings to configure s3proxy
        - name: S3PROXY_ENDPOINT
          value: http://0.0.0.0:8080
        - name: S3PROXY_AUTHORIZATION
          value: aws-v2-or-v4
        - name: S3PROXY_IDENTITY
          value: changeme
        - name: S3PROXY_CREDENTIAL
          value: changeme
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 1Gi
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: s3proxy
spec:
  ports:
  - name: http
    port: 8080
  selector:
    app: s3proxy
