apiVersion: v1
kind: Secret
metadata:
  name: s3proxy
type: Opaque
data:
  url: {{ default "" .Values.secret.url | b64enc | quote }}
  access_key: {{ default "" .Values.secret.access_key | b64enc | quote }}
  secret_key: {{ default "" .Values.secret.secret_key | b64enc | quote }}
  azure_account_name: {{ default ""  .Values.secret.azure_account_name | b64enc | quote }}
  azure_key: {{  default "" .Values.secret.azure_key | b64enc | quote }}

